retrospective experiments for sarix models
reichlab/flusion-experiments pull request #3
Opened 2024-10-31 16:49 UTC by elray1

varying p, theta pooling strategy, and covariate inclusion

2024-10-31 16:50 UTC, elray1 commented on code/sarix_model/configs/sarix_p2_4rt_thetanone_sigmanone.py
Becky's advice in previous PR for creating a setup based on dataclass with a helper function to instantiate class objects based on passed arguments came too late for this round of updates 😢

2024-10-31 16:51 UTC, elray1 commented on code/sarix_model/sarix_model.py
> +    batched_xy = df[xy_colnames].values.reshape(len(df['location'].unique()), -1, len(xy_colnames))
fixing a bug that surfaced when `model_config.x = []`; last dimension should just be 1 in that case.

2024-10-31 16:52 UTC, elray1 commented on retrospective-hub/model-output/UMass-sarix_p2_4rt_thetanone_sigmanone/2023-10-14-UMass-sarix_p2_4rt_thetanone_sigmanone.csv
everything from here on down is not really reviewable: it's model output files created from retrospective fits.

2024-10-31 16:52 UTC, elray1 commented on code/eval/score_sarix_retrospective.R
one-off/hasty evaluation script.  look at hubEvals being used in the wild!

2024-11-01 15:32 UTC, bsweger requested changes
Looks good, but am requesting a change from `os.system` to `subprocess.run` for security and usability reasons (the former is the reason for the change request).

Obviously there's no immediate security threat as you're running experiments, but it's a small change and is a good habit to get into.

2024-11-01 15:32 UTC, bsweger commented on code/sarix_model/retrospective-experiments/sarix_experiments.py
> +                for (model_name, ref_date) in product(model_names, ref_dates)]
`subprocess` is the recommended python module for running system commands (it's more secure, is more consistent across platforms, and is more flexible to work with in terms of handling command output and errors).

`subprocess.run` accepts a command list where each component of the command is an individual item. So if you refactor your list of commands along the lines of the suggestion below, you could swap in subprocess without too much effort (and could explore [its parameters](https://docs.python.org/3/library/subprocess.html#subprocess.run) should you ever need to reroute the output or add error handling)

```suggestion
def run_command(command):
    """Run system command"""
    subprocess.run(command)


output_root = '../../retrospective-hub/model-output'

commands = [[
    "python sarix_model.py",
    "--ref-date", ref_date,
    "--output_root", output_root,
    "--model_name", model_name]
    for (model_name, ref_date) in product(model_names, ref_dates)]
```

2024-11-05 22:55 UTC, bsweger approved these changes

2024-11-05 23:06 UTC, merged